#release configuration
#Thu Jun 18 17:04:14 CEST 2026
completedPhase=end-release
exec.activateProfiles=deploy-to-scijava
exec.additionalArguments=-Dgpg.skip\=true 
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.sc.fiji\:TrackMate-YOLO=1.0.5-SNAPSHOT
project.rel.sc.fiji\:TrackMate-YOLO=1.0.4
project.scm.sc.fiji\:TrackMate-YOLO.connection=scm\:git\:https\://github.com/trackmate-sc/TrackMate-YOLO
project.scm.sc.fiji\:TrackMate-YOLO.developerConnection=scm\:git\:git@github.com\:trackmate-sc/TrackMate-YOLO
project.scm.sc.fiji\:TrackMate-YOLO.tag=HEAD
project.scm.sc.fiji\:TrackMate-YOLO.url=https\://github.com/trackmate-sc/TrackMate-YOLO
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=TrackMate-YOLO-1.0.4
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/trackmate-sc/TrackMate-YOLO
